# Generated by Django 4.2.1 on 2023-05-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificacion",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="Identificacion"
                    ),
                ),
                ("nombre", models.CharField(max_length=20, verbose_name="Nombre")),
                (
                    "apellido",
                    models.CharField(max_length=20, null=True, verbose_name="Apellido"),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Telefono"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        max_length=50, null=True, unique=True, verbose_name="Direccion"
                    ),
                ),
            ],
        ),
    ]
