# Generated by Django 4.2.1 on 2023-05-10 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conductoresApp", "0001_initial"),
        ("vehiculosApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="conductor_id_3",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conductor_id_3",
                to="conductoresApp.conductor",
            ),
        ),
    ]
